apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: palestina
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: palestina
    newName: rg.fr-par.scw.cloud/djnd/palestina
    newTag: '265ff6bea2fa256cc633197afa4f77a528a76b8c'
