apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: palestina
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: palestina
    newName: rg.fr-par.scw.cloud/djnd/palestina
    newTag: '5c400048c9c6a5eb1da43f78b038013fc3fdb990'
